' ******************************************************************************
' swxJRNL.swj - journal recorded on 07/22/21 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Main.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1138782147158558106, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.04555128588634232284, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.05314316686739938705, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.09869445275374170989, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, -0.1214700956969128748, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03779728661350228308, -0.1897970245264263556, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03779728661350228308, -0.1973889055074834198, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.204980786488540484, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.1897970245264263556, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, -0.1897970245264263556, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.1290619766779699529, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.1062863337347987741, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.1062863337347987741, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.09110257177268464568, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.08351069079162759534, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.09110257177268464568, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.08351069079162759534, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.09110257177268464568, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.09110257177268464568, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.09110257177268464568, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06832692882951349467, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.06073504784845643739, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.2429401913938257496, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05314316686739938705, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, 0.04555128588634232284, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, 0.0303675239242282187, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, 0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, 0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, 0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04123340357836613457, 0.0303675239242282187, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01518376196211410935, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.0303675239242282187, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.05314316686739938705, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.04555128588634232284, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.0379594049052852725, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0303675239242282187, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0303675239242282187, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02277564294317116142, -0.02823623964471266845, 0.05811819991217248571, 0.02920000000011668817

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05497787143782150582, 0.09869445275374170989, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.06073504784845643739, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.0303675239242282187, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02277564294317116142, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007591880981057054674, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007591880981057054674, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.06832692882951349467, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.075918809810570545, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.075918809810570545, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.08351069079162759534, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.05314316686739938705, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.05314316686739938705, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.0379594049052852725, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.02277564294317116142, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.01518376196211410935, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01518376196211410935, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.02277564294317116142, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01518376196211410935, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.01518376196211410935, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01518376196211410935, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007591880981057054674, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007591880981057054674, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 0.08393263652010318765, 0.02675540387208741322, 0.07451707704876753269

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.01518376196211410935, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007591880981057054674, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007591880981057054674, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.007591880981057054674, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.007591880981057054674, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01518376196211410935, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.007591880981057054674, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.01518376196211410935, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, 0.04762186500753884388, 0.03744649607182992668, 0.09548111075605447695

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02277564294317116142, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02277564294317116142, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0303675239242282187, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04555128588634232284, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06073504784845643739, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06073504784845643739, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05314316686739938705, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.05314316686739938705, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.04555128588634232284, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0303675239242282187, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0303675239242282187, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.05314316686739938705, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04555128588634232284, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.06832692882951349467, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.08351069079162759534, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.09110257177268464568, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.06832692882951349467, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06832692882951349467, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.05314316686739938705, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.06832692882951349467, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.075918809810570545, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.075918809810570545, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.06073504784845643739, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06832692882951349467, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.06832692882951349467, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.04555128588634232284, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.0379594049052852725, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0303675239242282187, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.0115967604140507774, 0.4752999199148604248, 0.009618795915287137177

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01518376196211410935, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0.01518376196211410935, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.01518376196211410935, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01518376196211410935, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007591880981057054674, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.07580628333300865052, 0.4717756550005560712, 0.09594003643110227131

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.09964739198105147799, 0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.3161227607674736984, 0.3720021680717956469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.075918809810570545
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.1138782147158558106
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.06832692882951349467
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.0303675239242282187

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06832692882951349467, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.2353483104127686854, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.04555128588634232284, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.04555128588634232284, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0379594049052852725, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0379594049052852725, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0379594049052852725, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0379594049052852725, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.04555128588634232284, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.04555128588634232284, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.04555128588634232284, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.04555128588634232284, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.1476594832708997274, 0.05538974440839083968, 0.05394560031879791495

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.15183761962114109
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07903069019186842459, -0.2884914772801681071, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0303675239242282187, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0303675239242282187, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.04555128588634232284, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.04555128588634232284, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.04555128588634232284, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.04555128588634232284, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02277564294317116142, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0303675239242282187, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02277564294317116142, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0303675239242282187, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0303675239242282187, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.06073504784845643739, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06073504784845643739, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.06832692882951349467, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06073504784845643739, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.06073504784845643739, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.09110257177268464568, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.15183761962114109, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.1138782147158558106, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.1290619766779699529, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.08351069079162759534, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.08351069079162759534, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.06073504784845643739, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007591880981057054674, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01518376196211410935, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02277564294317116142, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01518376196211410935, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.0303675239242282187, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.0303675239242282187, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.04555128588634232284, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.05314316686739938705, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06073504784845643739, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.1138782147158558106, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1138782147158558106, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1062863337347987741, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08351069079162759534, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0379594049052852725, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07903069019186842459, -0.09110257177268464568, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 0.01991799913298564206, 0.2155906806888516769, 0.2118722184052330704

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
