' ******************************************************************************
' swxJRNL.swj - journal recorded on 07/22/21 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Main.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03779728661350228308, 0.4555128588634232423, 0.06802711967444707852, 0.2209052596136302782, 0.009131046602021797298
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1366538576590269893, 0.06802711967444707852, 0.2209052596136302782, 0.009131046602021797298
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, 0.06802711967444707852, 0.2209052596136302782, 0.009131046602021797298

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.0153712345078247381, 0.1689538355581845508, 0.02803295505071901061, -0.4990704350745174267, -0.150679208422330374, 0.8533606957106427693, 0.0001273581653456215762, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.0153712345078247381, 0.1689538355581845508, 0.02803295505071901061, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(-0.01465550144013150202, 0.168166445250903962, 0.02819357297812530305, -0.4990704350745174267, -0.150679208422330374, 0.8533606957106427693, 0.0001273581653456215762, 2, False, 0, 0)
Part.OpenCompFile

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\mobile-robot\ISC2021(new)\Cad Part Data\Linear Slide\MGN7\MGN7 rail.SLDPRT", 1, 0, "", longstatus, longwarnings)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 28
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "MGN7 rail.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.0002042487473303822298, 0.001692442695400586672, 0.04000000000002046363, -0.08112325903941969285, -0.7490120537233713183, -0.6575712586632119772, 0.0003857010954265777851, 2, False, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.07059758772111911218, -0.2429401913938257496
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02117927631633573227, -0.06073504784845643739
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01764939693027977805, -0.06832692882951349467
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02470915570239168649, -0.075918809810570545
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02117927631633573227, -0.075918809810570545
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02470915570239168649, -0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, -0.06832692882951349467
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01764939693027977805, -0.06073504784845643739
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, -0.06073504784845643739
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.1214700956969128748
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.1290619766779699529
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.1138782147158558106
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.1290619766779699529
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.1138782147158558106
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.09110257177268464568
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True

' Close Document
swPart = Nothing
Set Part = Nothing
swApp.CloseDoc "MGN7 rail.SLDPRT"
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "Main.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.075918809810570545, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.1062863337347987741, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.09110257177268464568, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.1138782147158558106, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.09869445275374170989, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.075918809810570545, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0303675239242282187, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0303675239242282187, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0303675239242282187, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0303675239242282187, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0303675239242282187, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0379594049052852725, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.05314316686739938705, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06832692882951349467, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.075918809810570545, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06832692882951349467, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.075918809810570545, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.06073504784845643739, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.06073504784845643739, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06073504784845643739, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.075918809810570545, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06073504784845643739, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06073504784845643739, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0303675239242282187, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.05314316686739938705, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.05314316686739938705, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.04555128588634232284, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02277564294317116142, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02277564294317116142, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007591880981057054674, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.02277564294317116142, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007591880981057054674, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007591880981057054674, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.05442709252781696705, 0.2001974100800225642, 0.005301101757993365027

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, 0.15183761962114109, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.06073504784845643739, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0379594049052852725, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06185010536754918797, 0.075918809810570545, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04810563750809381672, -0.1670213815832551907, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, -0.1290619766779699529, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0379594049052852725, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.01518376196211410935, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02277564294317116142, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0303675239242282187, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007591880981057054674, -0.06231285909353800889, 0.1654795457357067789, 0.0596527811088591875

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.2125726674695975482
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, 0.2960833582612251158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06832692882951349467
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.07145210346851627037, 0.1666773198719226912, 0.04884963574711775891, 0.9235794506917620605, -0.3203970327828323805, -0.2105866559016978945, 0.0003008184186846746635, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
boolstatus = Part.Extension.SelectByRay(-0.07245103614377512713, 0.167185734482643511, 0.0533010015401629289, 0.9235794506917620605, -0.3203970327828323805, -0.2105866559016978945, 0.0003008184186846746635, 2, False, 0, 0)
Part.OpenCompFile

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\mobile-robot\ISC2021(new)\Cad Part Data\Linear Slide\MGN7\MGN7 rail.SLDPRT", 1, 0, "", longstatus, longwarnings)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 28
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "MGN7 rail.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01764939693027977805, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.007591880981057054674

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02117927631633573227, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.00347076941120860738, 0.002206311064526289556, 0.02308702891330050022, 0.2110068780255182075, -0.9773082326655445629, 0.01856652337067753872, 3.051716331704593506e-05, 1, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Extrude1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.001366259339590669697, 0.002399999999965984898, 0.01283889940050197964, 0.1242603972558821851, -0.9922460720717883875, 0.00266197894766385338, 0.0002562955719378481813, 2, False, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.1897970245264263556
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.2808995962991110429
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03529879386055955609, -0.30367523924228218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04588843201872742222, -0.2201645484506545569
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.07765734649323101368, -0.204980786488540484
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.08824698465139887982, -0.15183761962114109
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0953067434235107952, -0.09110257177268464568
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03529879386055955609, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03882867324661550684, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04235855263267146453, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03882867324661550684, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06000794956295123911, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05294819079083932373, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0635378289490071968, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05647807017689528142, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05647807017689528142, 0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06000794956295123911, 0.06832692882951349467
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06706770833506314755, 0.1062863337347987741
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04941831140478337298, 0.075918809810570545
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04941831140478337298, 0.1290619766779699529
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04941831140478337298, 0.1366538576590269893
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04235855263267146453, 0.1670213815832551907
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03882867324661550684, 0.1897970245264263556
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02823903508844764071, 0.1746132625643122549
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02823903508844764071, 0.2353483104127686854
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02117927631633573227, 0.2125726674695975482
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0.1746132625643122549
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.2125726674695975482
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.1822051435453692914
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.2125726674695975482
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.1670213815832551907
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.1366538576590269893
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.1290619766779699529
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02117927631633573227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02823903508844764071, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02117927631633573227, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02823903508844764071, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0317689144745035984, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03882867324661550684, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03882867324661550684, -0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0317689144745035984, -0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03529879386055955609, -0.06073504784845643739
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, -0.06832692882951349467
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02823903508844764071, -0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, -0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02117927631633573227, -0.1062863337347987741
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, -0.09110257177268464568
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.1062863337347987741
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.09110257177268464568
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.09869445275374170989
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1062863337347987741
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.08351069079162759534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.06073504784845643739
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.05314316686739938705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02117927631633573227, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02823903508844764071, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02117927631633573227, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02117927631633573227, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02470915570239168649, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.04555128588634232284
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0.0379594049052852725
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01764939693027977805, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01764939693027977805, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01058963815816786613, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007059758772111910177, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02277564294317116142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02117927631633573227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02823903508844764071, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01764939693027977805, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01058963815816786613, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01411951754422382035, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007059758772111910177, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003529879386055955089, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0635378289490071968, -0.06073504784845643739
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02823903508844764071, -0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01764939693027977805, -0.01518376196211410935
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003529879386055955089, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0303675239242282187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007591880981057054674

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
' MSGBOX
' xs MGN7 rail.SLDPRT ?


' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
