' ******************************************************************************
' swxJRNL.swj - journal recorded on 07/23/21 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Gear mount.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0498804404608965482, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0341287224206134332, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04725515412084936584, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05250572680094374445, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.07350801752132123112, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.09188502190165154238, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.07350801752132123112, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.08138387654146279904, -0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.08925973556160435307, -0.1162062294602472234
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.1155125989620762322, -0.1478988374948600748
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.1050114536018874889, -0.1637451415121665421
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.08925973556160435307, -0.1373346348166558095
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.07613330386136842043, -0.1162062294602472234
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05513101314099092681, -0.09507782410383863736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.06300687216113248779, -0.1162062294602472234
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03675400876066061556, -0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, -0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.1942711891634918142, -0.1162062294602472234
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, -0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1003599254429407839
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0341287224206134332, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0341287224206134332, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0341287224206134332, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03937929510070780487, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04200458144075498723, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05513101314099092681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04200458144075498723, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06038158582108529848, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03675400876066061556, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0341287224206134332, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0498804404608965482, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0341287224206134332, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04462986778080217654, 0.1003599254429407839
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03675400876066061556, 0.1003599254429407839
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, 0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, 0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0.110924128121145063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.09507782410383863736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.110924128121145063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.1003599254429407839
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.1056420267820429165
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.12148833079934937
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.09507782410383863736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02100229072037749362, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02625286340047187222, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0341287224206134332, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0341287224206134332, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03937929510070780487, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03937929510070780487, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0341287224206134332, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02625286340047187222, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0341287224206134332, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.1003599254429407839
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.09507782410383863736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.1003599254429407839
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02887814974051905806, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0341287224206134332, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03675400876066061556, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02887814974051905806, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02887814974051905806, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, -0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, -0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0341287224206134332, -0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04725515412084936584, -0.09507782410383863736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, -0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03675400876066061556, -0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03675400876066061556, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05775629948103811612, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04462986778080217654, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03675400876066061556, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04200458144075498723, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02100229072037749362, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02100229072037749362, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, 0.110924128121145063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.110924128121145063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, 0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02887814974051905806, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03675400876066061556, 0.0739494187474300374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03937929510070780487, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02887814974051905806, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03937929510070780487, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04462986778080217654, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03937929510070780487, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03675400876066061556, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03937929510070780487, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02887814974051905806, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03150343608056624389, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02100229072037749362, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02625286340047187222, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02100229072037749362, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02625286340047187222, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\mobile-robot\ISC2021(new)\Main.SLDASM", 2, 0, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "Main.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04896466674930977786, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05927301764390130456, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04381049130201401104, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03865631585471824422, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04123340357836613457, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05669592992025343503, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05927301764390130456, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03865631585471824422, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007731263170943648497, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005154175447295766821, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005154175447295766821, -0.1056420267820429165
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005154175447295766821, -0.1531809388339622491
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01546252634188729699, -0.1743093441903708074
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01546252634188729699, -0.1373346348166558095
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01546252634188729699, -0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0180396140655351804, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0180396140655351804, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02834796496012671752, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04123340357836613457, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05154175447295766127, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.09535224577497167231, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.1262772984587462732, 0.1531809388339622491
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04896466674930977786, 0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01546252634188729699, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007731263170943648497, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02834796496012671752, 0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03607922813107036081, 0.06866731740832790476

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "Gear mount.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
swApp.ExitApp
End Sub
