' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/08/21 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Camera Mount 2.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0.1056420267820429165
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, 0.1056420267820429165
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.08451362142563433044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, 0.0792315200865321978
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, 0.08979572276473649084
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02625286340047187222, -0.1743093441903708074
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.12148833079934937
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.2535408642769029774
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.2535408642769029774
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.1743093441903708074
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Close Document
swPart = Nothing
Set Part = Nothing
swApp.CloseDoc "Camera Mount 2.SLDPRT"
swApp.ExitApp
End Sub
