' ******************************************************************************
' swxJRNL.swj - journal recorded on 07/23/21 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Gear mount.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02100229072037749362, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0341287224206134332, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03937929510070780487, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03150343608056624389, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02625286340047187222, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02887814974051905806, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02362757706042468292, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02100229072037749362, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01837700438033030778, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01575171804028312195, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01837700438033030778, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02625286340047187222, 0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02362757706042468292, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02100229072037749362, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01575171804028312195, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01312643170023593611, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
