' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/01/21 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "V-Slot 20x20x210 Linear Rail.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01050114536018874681, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01050114536018874681, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02100229072037749362, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04462986778080217654, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02625286340047187222, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02625286340047187222, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02625286340047187222, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02362757706042468292, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01575171804028312195, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02362757706042468292, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01575171804028312195, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007875859020141560973, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007875859020141560973, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007875859020141560973, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.02641050669551072913, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.02112840535640858261, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0.02641050669551072913, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.0369747093737150187, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.04225681071281716522, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.0369747093737150187, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0369747093737150187, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04753891205191931868, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05810311473012361172, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06338521606922574436, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05282101339102145826, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.0739494187474300374, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05282101339102145826, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.05282101339102145826, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.06338521606922574436, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.04225681071281716522, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.04225681071281716522, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.03169260803461287218, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.0369747093737150187, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.03169260803461287218, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.02112840535640858261, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.02112840535640858261, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01050114536018874681, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007875859020141560973, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01050114536018874681, -0.02112840535640858261, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007875859020141560973, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01837700438033030778, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005250572680094373404, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005250572680094373404, -0.0369747093737150187, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002625286340047186702, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02112840535640858261, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.02112840535640858261, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.02112840535640858261, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01056420267820429131, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002625286340047186702, 0, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005282101339102145653, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01584630401730643609, 0.008200000000044838089, 0.003757495673909261313, 0.002125408337860790198

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.008762004045223648063, 0.00762848548295380624, 0, 0.04340184891646568094, -0.01322779527181178021, 0.9989701221472438997, 0.0001257254992035455865, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.008577853772852250813, 0.007740832692952004379, 0, 0.04340184891646568094, -0.01322779527181178021, 0.9989701221472438997, 0.0001257254992035455865, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03937929510070780487, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007875859020141560973, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01050114536018874681, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, 0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02112840535640858261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, 0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01312643170023593611, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.02641050669551072913
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.04225681071281716522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01050114536018874681, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.04753891205191931868
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007875859020141560973, -0.1056420267820429165
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.1003599254429407839
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.06866731740832790476
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.05282101339102145826
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005250572680094373404, -0.06338521606922574436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.002625286340047186702, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.05810311473012361172
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0369747093737150187
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03169260803461287218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01584630401730643609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.01056420267820429131
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.005250572680094373404, -0.005282101339102145653
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.002625286340047186702, -0.005282101339102145653

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
